// AUTO-GENERATED by scripts/fetch-brand-logos.mjs — 직접 수정하지 마세요.
// 브랜드 id → 내려받은 로고 경로. 스크립트를 실행하면 채워집니다.
// (스크립트 실행 전에는 비어 있고, brands.ts 가 이 맵에 있는 브랜드만 활성화합니다.)
export const BRAND_ICONS: Record<string, string> = {};
