name = "aircon-democracy-next"
compatibility_date = "2026-05-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "aircon-democracy"
database_id = "daee340e-0b42-4141-93e4-c0c09077405b"
